In [1]:
from sklearn import datasets, svm
from sklearn.model_selection import train_test_split
import numpy as np

In [2]:
digit=datasets.load_digits()
x_train, x_test, y_train, y_test = train_test_split(digit.data, digit.target, train_size= 0.6)

In [5]:
s =svm.SVC(gamma=0.001)
s.fit(x_train, y_train)

res = s.predict(x_test)

conf = np.zeros((10,10))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

no_correct = 0
for i in range(10):
    no_correct += conf[i][i]
accuracy = no_correct/len(res)
print("테스트 정확률", accuracy*100,"%desu")

[[67.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 84.  0.  0.  0.  0.  0.  0.  2.  0.]
 [ 0.  0. 65.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. 71.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 69.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0. 72.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. 73.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. 73.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0. 69.  0.]
 [ 0.  0.  0.  0.  0.  2.  0.  1.  0. 69.]]
테스트 정확률 99.02642559109874 %desu


In [45]:
#iris 데이터
iris=datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size= 0.6)

In [48]:
s =svm.SVC(gamma=0.317)
s.fit(x_train, y_train)

res = s.predict(x_test)

conf = np.zeros((3,3))
for i in range(len(res)):
    conf[res[i]][y_test[i]]+=1
print(conf)

no_correct = 0
for i in range(3):
    no_correct += conf[i][i]
accuracy = no_correct/len(res)

print("테스트 정확률", accuracy*100,"%desu")

[[23.  0.  0.]
 [ 0. 18.  1.]
 [ 0.  0. 18.]]
테스트 정확률 98.33333333333333 %desu


In [47]:
gam = 0.001
praccu = 0
maxgam = 0
for j in range(1001):
    s =svm.SVC(gamma=gam)
    gam += 0.001
    s.fit(x_train, y_train)

    res = s.predict(x_test)

    conf = np.zeros((3,3))
    for i in range(len(res)):
        conf[res[i]][y_test[i]]+=1

    no_correct = 0
    for i in range(3):
        no_correct += conf[i][i]
    accuracy = no_correct/len(res)
    if praccu < accuracy:
        print(j+1 ,"번째 gamma : ", gam , "테스트 정확률", accuracy*100,"%desu")
        praccu = accuracy
        maxgam = gam
    if j == 999:
        print("end")

1 번째 gamma :  0.002 테스트 정확률 30.0 %desu
2 번째 gamma :  0.003 테스트 정확률 68.33333333333333 %desu
3 번째 gamma :  0.004 테스트 정확률 76.66666666666667 %desu
4 번째 gamma :  0.005 테스트 정확률 86.66666666666667 %desu
11 번째 gamma :  0.012000000000000004 테스트 정확률 88.33333333333333 %desu
12 번째 gamma :  0.013000000000000005 테스트 정확률 91.66666666666666 %desu
13 번째 gamma :  0.014000000000000005 테스트 정확률 93.33333333333333 %desu
34 번째 gamma :  0.035000000000000024 테스트 정확률 95.0 %desu
36 번째 gamma :  0.037000000000000026 테스트 정확률 96.66666666666667 %desu
316 번째 gamma :  0.3170000000000002 테스트 정확률 98.33333333333333 %desu
end
